
GAL16V8B
A EXAMPLE for clock logic
2020-02-17，by xinkai
e-mail:aakwxk@hotmail.com
  Array Input pin        1   1   1   1   1   1   1   1 
                       2 9 3 8 4 7 5 6 6 5 7 4 8 3 9 2 

Polarity Fuse X
AC1 Fuse -
 Output Pin 19 Row 0   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 19 Row 1   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 19 Row 2   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 19 Row 3   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 19 Row 4   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 19 Row 5   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 19 Row 6   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 19 Row 7   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Polarity Fuse -
AC1 Fuse X
 Output Pin 18 Row 0   X-----X-----------------------X-
 Output Pin 18 Row 1   -X----X------------------------X
 Output Pin 18 Row 2   -----XX-------------------------
 Output Pin 18 Row 3   X---X-----X--------------------X
 Output Pin 18 Row 4   -X--X---------------------X---X-
 Output Pin 18 Row 5   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 18 Row 6   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 18 Row 7   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Polarity Fuse -
AC1 Fuse X
 Output Pin 17 Row 0   X---------X-------------------X-
 Output Pin 17 Row 1   -X--------X--------------------X
 Output Pin 17 Row 2   -----X----X---------------------
 Output Pin 17 Row 3   X---X---------X----------------X
 Output Pin 17 Row 4   -X--X-X-----------------------X-
 Output Pin 17 Row 5   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 17 Row 6   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 17 Row 7   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Polarity Fuse -
AC1 Fuse X
 Output Pin 16 Row 0   X-------------X---------------X-
 Output Pin 16 Row 1   -X------------X----------------X
 Output Pin 16 Row 2   -----X--------X-----------------
 Output Pin 16 Row 3   X---X-------------X------------X
 Output Pin 16 Row 4   -X--X-----X-------------------X-
 Output Pin 16 Row 5   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 16 Row 6   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 16 Row 7   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


GAL16V8B
A EXAMPLE for clock logic
2020-02-17，by xinkai
e-mail:aakwxk@hotmail.com
  Array Input pin        1   1   1   1   1   1   1   1 
                       2 9 3 8 4 7 5 6 6 5 7 4 8 3 9 2 

Polarity Fuse -
AC1 Fuse X
 Output Pin 15 Row 0   X-----------------X-----------X-
 Output Pin 15 Row 1   -X----------------X------------X
 Output Pin 15 Row 2   -----X------------X-------------
 Output Pin 15 Row 3   X---X-----------------X--------X
 Output Pin 15 Row 4   -X--X---------X---------------X-
 Output Pin 15 Row 5   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 15 Row 6   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 15 Row 7   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Polarity Fuse -
AC1 Fuse X
 Output Pin 14 Row 0   X---------------------X-------X-
 Output Pin 14 Row 1   -X--------------------X--------X
 Output Pin 14 Row 2   -----X----------------X---------
 Output Pin 14 Row 3   X---X---------------------X----X
 Output Pin 14 Row 4   -X--X-------------X-----------X-
 Output Pin 14 Row 5   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 14 Row 6   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 14 Row 7   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Polarity Fuse -
AC1 Fuse X
 Output Pin 13 Row 0   -------X---X---X---X---X--------
 Output Pin 13 Row 1   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 13 Row 2   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 13 Row 3   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 13 Row 4   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 13 Row 5   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 13 Row 6   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 13 Row 7   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Polarity Fuse -
AC1 Fuse X
 Output Pin 12 Row 0   X-------------------------------
 Output Pin 12 Row 1   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 12 Row 2   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 12 Row 3   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 12 Row 4   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 12 Row 5   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 12 Row 6   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 Output Pin 12 Row 7   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 SYN Fuse X
 AC0 Fuse -
